[aws]
# profile_name = "cloudflare-r2"
endpoint_url = "https://262cf8aeb384b1f034577956e3baa60a.r2.cloudflarestorage.com"

[aws.s3]
bucket_name = "rwx-pub"
public_url = "https://pub.rwx.im"

[database]
url = "postgres://meta_ingress:ch4ngem3@localhost:5432/meta_ingress_development"

[ingestion]
api_token = "hello-world"

[meta_webhook]
token = ""

[tracing]
enabled = true

[auth]
issuer_url = "https://rwx-prod.eu.auth0.com/"
client_id = "5HqyKOfK4ULgEuTFvomHvoNjZduCJ98w"
client_secret = "redacted"
redirect_url = "http://localhost:3000/auth/callback"
